// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0y6UUJjoTuSf9EJJ_zYcDZQpKnt5Nk08',
    appId: '1:427363264658:web:37469b2d82b23196e21e4b',
    messagingSenderId: '427363264658',
    projectId: 'messenger-app-a7df2',
    authDomain: 'messenger-app-a7df2.firebaseapp.com',
    storageBucket: 'messenger-app-a7df2.firebasestorage.app',
    measurementId: 'G-Z21KJDEY0P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjOWTR2u_VV-DZNsAIW6-Uip2nIdUxllA',
    appId: '1:427363264658:android:5b4246f973f29b67e21e4b',
    messagingSenderId: '427363264658',
    projectId: 'messenger-app-a7df2',
    storageBucket: 'messenger-app-a7df2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAl1ndPXR5DHfp8uNlvaFvXCYHozoEC-A',
    appId: '1:427363264658:ios:cfc460a150298653e21e4b',
    messagingSenderId: '427363264658',
    projectId: 'messenger-app-a7df2',
    storageBucket: 'messenger-app-a7df2.firebasestorage.app',
    iosBundleId: 'com.example.messageBoardApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAl1ndPXR5DHfp8uNlvaFvXCYHozoEC-A',
    appId: '1:427363264658:ios:cfc460a150298653e21e4b',
    messagingSenderId: '427363264658',
    projectId: 'messenger-app-a7df2',
    storageBucket: 'messenger-app-a7df2.firebasestorage.app',
    iosBundleId: 'com.example.messageBoardApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0y6UUJjoTuSf9EJJ_zYcDZQpKnt5Nk08',
    appId: '1:427363264658:web:c214259ab8ec4014e21e4b',
    messagingSenderId: '427363264658',
    projectId: 'messenger-app-a7df2',
    authDomain: 'messenger-app-a7df2.firebaseapp.com',
    storageBucket: 'messenger-app-a7df2.firebasestorage.app',
    measurementId: 'G-W9GPZYCH9B',
  );
}
